apiVersion: v1
kind: Service
metadata:
  name: ui-tier
  labels:
    app: microservices
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30002
  selector:
    tier: ui